### ISSUE TITLE
Infotext linke Seite

### ISSUE THREAD

**Issue by od-ms** [digifarm-ms/giessdenkiez-de#4]
**Über das Projekt**

Die Folgen des Klimawandels, insbesondere die trockenen und heißen Sommer, belasten das Münsteraner Ökosystem. Unsere Stadtbäume vertrocknen und tragen langfristige Schäden davon: In den letzten Jahren mussten immer mehr Bäume gefällt werden und ihre Lebensdauer sinkt. Inzwischen wird die Bevölkerung regelmäßig zur Unterstützung aufgerufen, allerdings weitgehend unkoordiniert. Dies möchten wir ändern und mit diesem Projekt eine koordinierte Beteiligung von Bürgerinnen und Bürgern bei der Bewässerung städtischen Grüns ermöglichen.

**Über uns**

„Gieß den Kiez” ist ein Projekt des [CityLAB Berlin](https://www.citylab-berlin.org/) / Technologiestiftung Berlin. Diese App wurde dort ohne kommerzielle Interessen als Open-Source-Software entwickelt, damit sie nicht nur in Berlin, sondern auch in anderen Kommunen wie Münster genutzt und weiterentwickelt werden kann.

Die Adaption und Installation von „Gieß den Kiez“ für Münster wurde umgesetzt im Rahmen des Projektes [DIGIFARM.MS](https://www.digifarm.ms). 
DIGIFARM.MS ist eine Maßnahme der Bundesförderung „[Modellprojekte Smart Cities](https://smartcity.ms/modellprojekte-smart-cities/)“, gefördert duch: 
- Logo vom Ministerium 
- Logo der KfW (s.u.)

**Datenquellen**

Die Karte zeigt die Münsteraner Straßenbäume. Zusätzlich wird abgebildet, wie viel Niederschlag in den letzten 30 Tagen bei jedem Baum gefallen ist und ob diese in dieser Zeit bereits gegossen wurden.

**Fragen & Antworten**

[Hier..LINK TBD](https://github.com/digifarm-ms/giessdenkiez-de/wiki) findest Du viele Tipps und Infos zum Gießen, zu Bäumen und zum Kontakt mit Anderen, die ebenfalls gießen.

![KfW_RGB](https://github.com/digifarm-ms/giessdenkiez-de/assets/50825288/cd717417-4c8f-48cb-9621-f3d3804ca152)

**Comment by sjockers** [comment]
Das Logo des Ministeriums fehlt noch. Könntet ihr das zur Verfügung stellen?

**Comment by sjockers** [comment]
@od-ms Ich habe das Logo selbst rausgesucht. Am besten ihr prüft, ob das so den Anforderungen eurer Förderung genügt.
