### ISSUE TITLE
Repositories auf OpenCoDE spiegeln

### ISSUE THREAD

**Issue by Smart-City-Muenster** [digifarm-ms/giessdenkiez-de#6]
Bitte mindestens einen Snapshot der finalen Repos unter https://gitlab.opencode.de/smart-city-muenster/digifarm.ms/muenster-schenkt-aus ablegen.

**Comment by sjockers** [comment]
Done: https://gitlab.opencode.de/smart-city-muenster/digifarm.ms/muenster-schenkt-aus
